// <auto-generated />
using System;
using ERP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP.Migrations
{
    [DbContext(typeof(ManufacturingDbContext))]
    [Migration("20260406070121_TotalQuantityupdatetodecimal")]
    partial class TotalQuantityupdatetodecimal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERP.Entity.BillOfMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("BillOfMaterials");
                });

            modelBuilder.Entity("ERP.Entity.BillOfMaterialItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillOfMaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BillOfMaterialId");

                    b.HasIndex("ComponentId");

                    b.ToTable("BillOfMaterialItems");
                });

            modelBuilder.Entity("ERP.Entity.Contact.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DefaultLeadTimeInDays")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("ERP.Entity.Contact.ProductSupplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("bit");

                    b.Property<int>("LeadTimeInDays")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SupplierId");

                    b.ToTable("ProductSuppliers");
                });

            modelBuilder.Entity("ERP.Entity.Document.GoodsReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("QuantityReceived")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("GoodsReceipts");
                });

            modelBuilder.Entity("ERP.Entity.Document.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpectedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("ERP.Entity.Document.PurchaseOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("QuantityReceived")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QuantityRequested")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("SalesOrderItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("SalesOrderItemId");

                    b.ToTable("PurchaseOrderItems");
                });

            modelBuilder.Entity("ERP.Entity.Document.SalesOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PurchaseOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReservationStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalFulfilledQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("SalesOrders");
                });

            modelBuilder.Entity("ERP.Entity.Document.SalesOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("QuantityFulfilled")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QuantityRequested")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QuantityReserved")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SalesOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SalesOrderId");

                    b.ToTable("SalesOrderItems");
                });

            modelBuilder.Entity("ERP.Entity.FinishedGoodsReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("FinishedGoodsReceipts");
                });

            modelBuilder.Entity("ERP.Entity.MaterialConsumption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ConsumedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ConsumptionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PlannedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("MaterialConsumptions");
                });

            modelBuilder.Entity("ERP.Entity.MrpPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AvailableQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PlannedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PlannedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductionOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PurchaseOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RequiredDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RequiredQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SalesOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("MrpPlans");
                });

            modelBuilder.Entity("ERP.Entity.Product.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("ERP.Entity.Product.StockTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("StockTransactions");
                });

            modelBuilder.Entity("ERP.Entity.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsManufactured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPurchasable")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MainProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MainProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ERP.Entity.ProductStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aisle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("None");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("QuantityAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("QuantityExpired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("QuantityInProduction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("QuantityQuarantined")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("QuantityRejected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.0m);

                    b.Property<decimal>("QuantityReserved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.0m);

                    b.Property<string>("Rack")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("None");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Shelf")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("None");

                    b.Property<string>("Warehouse")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("None");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("None");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductStocks");
                });

            modelBuilder.Entity("ERP.Entity.ProductionOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("ProductionOperations");
                });

            modelBuilder.Entity("ERP.Entity.ProductionOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualFinishDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("BillOfMaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("PlannedFinishDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PlannedQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("PlannedStartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ProducedQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("SalesOrderItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BillOfMaterialId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SalesOrderItemId");

                    b.ToTable("ProductionOrders");
                });

            modelBuilder.Entity("ERP.Entity.Settings.InventorySettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowOverFulfill")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowPartialFulfillment")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoFulfillOnReceive")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoReserveOnReceive")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoRunMrpOnReceive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("InventorySettings");
                });

            modelBuilder.Entity("ERP.Entity.UnitOfMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnitOfMeasures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AI",
                            IsActive = false,
                            Name = "Assembled Item"
                        },
                        new
                        {
                            Id = 2,
                            Code = "L",
                            IsActive = false,
                            Name = "Liter"
                        },
                        new
                        {
                            Id = 3,
                            Code = "cl",
                            IsActive = false,
                            Name = "Centiliter"
                        },
                        new
                        {
                            Id = 4,
                            Code = "ml",
                            IsActive = false,
                            Name = "Mililiter"
                        },
                        new
                        {
                            Id = 5,
                            Code = "dl",
                            IsActive = false,
                            Name = "Deciliter"
                        },
                        new
                        {
                            Id = 6,
                            Code = "dcl",
                            IsActive = false,
                            Name = "Decaliter"
                        },
                        new
                        {
                            Id = 7,
                            Code = "hcl",
                            IsActive = false,
                            Name = "Hectoliter"
                        },
                        new
                        {
                            Id = 8,
                            Code = "kl",
                            IsActive = false,
                            Name = "Kiloliter"
                        },
                        new
                        {
                            Id = 9,
                            Code = "pt",
                            IsActive = false,
                            Name = "Pint"
                        },
                        new
                        {
                            Id = 10,
                            Code = "gll",
                            IsActive = false,
                            Name = "Gallon (Metric)"
                        },
                        new
                        {
                            Id = 11,
                            Code = "glim",
                            IsActive = false,
                            Name = "Gallon (Imperial)"
                        },
                        new
                        {
                            Id = 12,
                            Code = "mcg",
                            IsActive = false,
                            Name = "Microgram"
                        },
                        new
                        {
                            Id = 13,
                            Code = "mg",
                            IsActive = false,
                            Name = "Milligram"
                        },
                        new
                        {
                            Id = 14,
                            Code = "g",
                            IsActive = false,
                            Name = "Gram"
                        },
                        new
                        {
                            Id = 15,
                            Code = "kg",
                            IsActive = false,
                            Name = "Kilogram"
                        },
                        new
                        {
                            Id = 16,
                            Code = "lb",
                            IsActive = false,
                            Name = "Pound"
                        },
                        new
                        {
                            Id = 17,
                            Code = "mt",
                            IsActive = false,
                            Name = "Metric-Ton"
                        },
                        new
                        {
                            Id = 18,
                            Code = "mm",
                            IsActive = false,
                            Name = "Millimeter"
                        },
                        new
                        {
                            Id = 19,
                            Code = "cm",
                            IsActive = false,
                            Name = "Centimeter"
                        },
                        new
                        {
                            Id = 20,
                            Code = "dm",
                            IsActive = false,
                            Name = "Decimeter"
                        },
                        new
                        {
                            Id = 21,
                            Code = "m",
                            IsActive = false,
                            Name = "Meter"
                        },
                        new
                        {
                            Id = 22,
                            Code = "dcm",
                            IsActive = false,
                            Name = "Decameter"
                        },
                        new
                        {
                            Id = 23,
                            Code = "hcm",
                            IsActive = false,
                            Name = "Hectometer"
                        },
                        new
                        {
                            Id = 24,
                            Code = "km",
                            IsActive = false,
                            Name = "Kilometer"
                        },
                        new
                        {
                            Id = 25,
                            Code = "in",
                            IsActive = false,
                            Name = "Inch"
                        },
                        new
                        {
                            Id = 26,
                            Code = "ft",
                            IsActive = false,
                            Name = "Foot"
                        },
                        new
                        {
                            Id = 27,
                            Code = "Yarn",
                            IsActive = false,
                            Name = "Yarn"
                        },
                        new
                        {
                            Id = 28,
                            Code = "Thread",
                            IsActive = false,
                            Name = "Thread"
                        },
                        new
                        {
                            Id = 29,
                            Code = "Yield",
                            IsActive = false,
                            Name = "Yield"
                        },
                        new
                        {
                            Id = 30,
                            Code = "Mommes",
                            IsActive = false,
                            Name = "Mommes"
                        },
                        new
                        {
                            Id = 31,
                            Code = "Quire",
                            IsActive = false,
                            Name = "Quire"
                        },
                        new
                        {
                            Id = 32,
                            Code = "Bulk",
                            IsActive = false,
                            Name = "Bulk"
                        },
                        new
                        {
                            Id = 33,
                            Code = "SI",
                            IsActive = false,
                            Name = "Single Item"
                        },
                        new
                        {
                            Id = 34,
                            Code = "SU",
                            IsActive = false,
                            Name = "Single Unit"
                        },
                        new
                        {
                            Id = 35,
                            Code = "t",
                            IsActive = false,
                            Name = "Ton"
                        },
                        new
                        {
                            Id = 36,
                            Code = "m2",
                            IsActive = false,
                            Name = "Square Meter"
                        },
                        new
                        {
                            Id = 37,
                            Code = "ha",
                            IsActive = false,
                            Name = "Hectare"
                        },
                        new
                        {
                            Id = 38,
                            Code = "km2",
                            IsActive = false,
                            Name = "Square Kilometer"
                        },
                        new
                        {
                            Id = 39,
                            Code = "cm3",
                            IsActive = false,
                            Name = "Cubic Centimeter"
                        },
                        new
                        {
                            Id = 40,
                            Code = "m3",
                            IsActive = false,
                            Name = "Cubic Meter"
                        },
                        new
                        {
                            Id = 41,
                            Code = "kg/m3",
                            IsActive = false,
                            Name = "Kilogram Per Cubic Meter"
                        },
                        new
                        {
                            Id = 42,
                            Code = "each",
                            IsActive = false,
                            Name = "Each"
                        },
                        new
                        {
                            Id = 43,
                            Code = "yard",
                            IsActive = false,
                            Name = "Yard"
                        },
                        new
                        {
                            Id = 44,
                            Code = "piece",
                            IsActive = false,
                            Name = "Piece"
                        },
                        new
                        {
                            Id = 45,
                            Code = "pair",
                            IsActive = false,
                            Name = "Pair"
                        },
                        new
                        {
                            Id = 46,
                            Code = "oz",
                            IsActive = false,
                            Name = "Ounce"
                        },
                        new
                        {
                            Id = 47,
                            Code = "floz",
                            IsActive = false,
                            Name = "Fluid Ounce"
                        },
                        new
                        {
                            Id = 48,
                            Code = "ac",
                            IsActive = false,
                            Name = "Acre"
                        },
                        new
                        {
                            Id = 49,
                            Code = "lot",
                            IsActive = false,
                            Name = "Lot"
                        },
                        new
                        {
                            Id = 50,
                            Code = "sin",
                            IsActive = false,
                            Name = "Square Inch"
                        },
                        new
                        {
                            Id = 51,
                            Code = "Other",
                            IsActive = false,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("ERP.Entity.BillOfMaterial", b =>
                {
                    b.HasOne("ERP.Entity.ProductEntity", "Product")
                        .WithMany("BOMs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ERP.Entity.BillOfMaterialItem", b =>
                {
                    b.HasOne("ERP.Entity.BillOfMaterial", "BillOfMaterial")
                        .WithMany("Items")
                        .HasForeignKey("BillOfMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Entity.ProductEntity", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillOfMaterial");

                    b.Navigation("Component");
                });

            modelBuilder.Entity("ERP.Entity.Contact.ProductSupplier", b =>
                {
                    b.HasOne("ERP.Entity.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Entity.Contact.Contact", "Supplier")
                        .WithMany("ProductSuppliers")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ERP.Entity.Document.GoodsReceipt", b =>
                {
                    b.HasOne("ERP.Entity.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Entity.Document.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("ERP.Entity.Document.PurchaseOrder", b =>
                {
                    b.HasOne("ERP.Entity.Contact.Contact", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ERP.Entity.Document.PurchaseOrderItem", b =>
                {
                    b.HasOne("ERP.Entity.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Entity.Document.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Entity.Document.SalesOrderItem", "SalesOrderItem")
                        .WithMany("PurchaseOrderItems")
                        .HasForeignKey("SalesOrderItemId");

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("SalesOrderItem");
                });

            modelBuilder.Entity("ERP.Entity.Document.SalesOrderItem", b =>
                {
                    b.HasOne("ERP.Entity.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Entity.Document.SalesOrder", "SalesOrder")
                        .WithMany("Items")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("ERP.Entity.FinishedGoodsReceipt", b =>
                {
                    b.HasOne("ERP.Entity.ProductionOrder", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ERP.Entity.MaterialConsumption", b =>
                {
                    b.HasOne("ERP.Entity.ProductionOrder", "Order")
                        .WithMany("Materials")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ERP.Entity.Product.Price", b =>
                {
                    b.HasOne("ERP.Entity.ProductEntity", "Product")
                        .WithMany("Prices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ERP.Entity.ProductEntity", b =>
                {
                    b.HasOne("ERP.Entity.ProductEntity", "MainProduct")
                        .WithMany("Variants")
                        .HasForeignKey("MainProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MainProduct");
                });

            modelBuilder.Entity("ERP.Entity.ProductStock", b =>
                {
                    b.HasOne("ERP.Entity.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ERP.Entity.ProductionOperation", b =>
                {
                    b.HasOne("ERP.Entity.ProductionOrder", "Order")
                        .WithMany("Operations")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ERP.Entity.ProductionOrder", b =>
                {
                    b.HasOne("ERP.Entity.BillOfMaterial", "BillOfMaterials")
                        .WithMany()
                        .HasForeignKey("BillOfMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Entity.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Entity.Document.SalesOrderItem", "SalesOrderItem")
                        .WithMany("ProductionOrders")
                        .HasForeignKey("SalesOrderItemId");

                    b.Navigation("BillOfMaterials");

                    b.Navigation("Product");

                    b.Navigation("SalesOrderItem");
                });

            modelBuilder.Entity("ERP.Entity.BillOfMaterial", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ERP.Entity.Contact.Contact", b =>
                {
                    b.Navigation("ProductSuppliers");

                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("ERP.Entity.Document.PurchaseOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ERP.Entity.Document.SalesOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ERP.Entity.Document.SalesOrderItem", b =>
                {
                    b.Navigation("ProductionOrders");

                    b.Navigation("PurchaseOrderItems");
                });

            modelBuilder.Entity("ERP.Entity.ProductEntity", b =>
                {
                    b.Navigation("BOMs");

                    b.Navigation("Prices");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("ERP.Entity.ProductionOrder", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
