services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: erp
      POSTGRES_PASSWORD: erp_secret
      POSTGRES_DB: erp_identity
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: erp
      RABBITMQ_DEFAULT_PASS: erp_secret

  identity-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.Identity
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__IdentityDb: Host=postgres;Port=5432;Database=erp_identity;Username=erp;Password=erp_secret
      Jwt__SecretKey: EnterpriseDevSecretKey_ChangeInProduction_Min32Chars!
    ports:
      - "5101:8080"
    depends_on:
      - postgres
      - redis
      - rabbitmq

  product-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.Product
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__ProductDb: Host=postgres;Port=5432;Database=erp_product;Username=erp;Password=erp_secret
      Jwt__SecretKey: EnterpriseDevSecretKey_ChangeInProduction_Min32Chars!
    ports:
      - "5103:8080"
    depends_on:
      - postgres

  inventory-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.Inventory
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__InventoryDb: Host=postgres;Port=5432;Database=erp_inventory;Username=erp;Password=erp_secret
      Jwt__SecretKey: EnterpriseDevSecretKey_ChangeInProduction_Min32Chars!
      RabbitMq__Host: rabbitmq
      RabbitMq__Username: erp
      RabbitMq__Password: erp_secret
    ports:
      - "5104:8080"
    depends_on:
      - postgres
      - rabbitmq

  manufacturing-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.Manufacturing
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__ManufacturingDb: Host=postgres;Port=5432;Database=erp_manufacturing;Username=erp;Password=erp_secret
      Jwt__SecretKey: EnterpriseDevSecretKey_ChangeInProduction_Min32Chars!
      RabbitMq__Host: rabbitmq
      RabbitMq__Username: erp
      RabbitMq__Password: erp_secret
    ports:
      - "5107:8080"
    depends_on:
      - postgres
      - rabbitmq

  gateway:
    build:
      context: ..
      dockerfile: docker/Dockerfile.Gateway
    ports:
      - "5000:8080"
    depends_on:
      - identity-api
      - product-api
      - inventory-api
      - manufacturing-api

volumes:
  pgdata:
